Repository wecode-bootcamp-korea/28-1st-DRHEEWON-frontend, pull requests merged in 2022-01, with the labels that each got.

#5 [28기 강희원] [Add] 회원가입 유효성 검사
  src/Router.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#9 [28기 강희원][Add] 로그인 버튼 활성화, 컴포넌트 분리
  src/components/RegisterLogin/ContentHeader.js
  src/components/RegisterLogin/Welcome.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#13 [28기 강희원][Modify] 백엔드 통신, 컴포넌트 분리, 병합 후 css 수정
  src/components/RegisterLogin/RegisterLogin.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
  src/styles/baseStyle/size.scss
Labels: Status: 리뷰 요청

#4 [28기 이석호] Add & Modify: 사이즈&컬러 버튼, 수량 카운터, 상품설명 구현 / 파트별 컴포넌트화
  .vscode/settings.json
  public/ProductDetail/centerColor/centerColor.json
  public/ProductDetail/centerSize/centerSize.json
  public/ProductDetail/drmartens1.jpeg
  public/ProductDetail/drmartens2.jpeg
  public/ProductDetail/drmartens3.jpeg
  public/ProductDetail/drmartens4.jpeg
  public/ProductDetail/drmartens5.jpeg
  public/ProductDetail/product/jaden.json
  public/ProductDetail/product/review.json
  src/Router.js
  src/pages/Main/Main.scss
  src/pages/ProductDetail/ProductContent/ProductContent.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductExplain/ProductExplain.js
  src/pages/ProductDetail/SlideShow/SlideShow.js
Labels: Status: Accepted, Status: 추가 기능 구현중

#6 [28기 김용선] [Modify] List page 상품 리스트 map 함수화 코드 수정중
  package.json
  public/data/itemData.json
  public/img/dummyImg.jpg
  src/Router.js
  src/components/ProductList/CategoryButton.js
  src/components/ProductList/Filter.js
  src/components/ProductList/FilterButton.js
  src/components/ProductList/MainContainer.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: Status: 도움 요청, Status: 리뷰 요청

#17 [28기 강희원][Add] 백엔드 통신
  src/pages/Login/Login.js
Labels: Status: Accepted

#18 [28기 김정현][Add] FlexibleSlider.js skeleton UI 적용 및 라우팅 경로 추가 등
  src/components/FlexibleSlider/BestIconSkeleton.js
  src/components/FlexibleSlider/FlexibleSlider.js
  src/components/FlexibleSlider/FlexibleSliderSkeleton.scss
  src/components/FlexibleSlider/MdRecommendSkeleton.js
  src/pages/Main/FlexibleSliderDetails/MainBestIconDetail.js
  src/pages/Main/FlexibleSliderDetails/MainMdRecommendDetail.js
  src/pages/Main/MainFlexSliderFetch.js
  src/pages/Main/MainMixin.scss
  src/pages/Main/MainNewJoin.js
Labels: Status: Accepted

#14 [28기 강희원][Add] 장바구니 Mark Up & Style 적용
  public/data/cartList/cartList.json
  src/Router.js
  src/components/RegisterLogin/ContentHeader.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartList.js
  src/pages/Cart/ProductPrice.js
  src/pages/Cart/SelectCart.js
  src/pages/Login/Login.js
  src/pages/Register/Register.js
Labels: Status: Accepted

#15 [28기 김정현][Refactor] 분리 가능한 useEffect 동작 hook으로 분리.
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavHiddenHorizontal/HorizontalContent.js
  src/components/Nav/NavHiddenHorizontal/HorizontalContent.scss
  src/components/Nav/NavHiddenMenu.js
  src/components/Nav/NavHiddenMenu.scss
  src/components/Nav/NavHiddenVertical/VerticalContent.js
  src/components/Nav/NavHiddenVertical/VerticalContent.scss
  src/components/Nav/NavHiddenVertical/VerticalItems.js
  src/components/Nav/NavMockData.js
  src/components/customlib/SetClassCondition.js
  src/components/customlib/SetQueryCondition.js
  src/components/customlib/SetQueryString.js
  src/config/config.json
  src/hooks/useHorizontalScroll.js
  src/hooks/useScrollHidden.js
  src/hooks/useToggleNav.js
  src/hooks/useVerticalScroll.js
Labels: Status: Accepted

#19 [28기 이석호] Modify: 상품 후기 구현 완료(stats 막대그래프, 코멘트 추가)
  public/ProductDetail/avatar1.jpeg
  public/ProductDetail/avatar2.jpeg
  public/ProductDetail/avatar3.jpeg
  public/ProductDetail/product/review.json
  public/ProductDetail/review/reviewStats.json
  public/ProductDetail/review/userReview.json
  src/pages/ProductDetail/ProductContent/ProductContent.js
  src/pages/ProductDetail/ProductContent/ProductContent.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductExplain/ProductExplain.scss
  src/pages/ProductDetail/SlideShow/SlideShow.js
  src/pages/ProductDetail/SlideShow/SlideShow.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#20 [28기 김정현][Modify] StickyArea scroll 동작 반응형으로 변경 등
  public/data/bestIcon1.json
  public/data/bestIcon2.json
  public/data/bestIcon3.json
  public/data/bestIcon4.json
  public/data/bestIcon5.json
  public/data/bestIcon6.json
  public/data/mdRecommend1.json
  public/data/mdRecommend2.json
  public/data/mdRecommend3.json
  public/data/mdRecommend4.json
  src/components/FlexibleSlider/FlexibleSlider.js
  src/pages/Main/FlexibleSliderDetails/MainBestIconDetail.js
  src/pages/Main/Main.scss
  src/pages/Main/MainFlexSliderFetch.js
  src/pages/Main/MainFullSlider.js
  src/pages/Main/MainMockData.js
  src/pages/Main/MainStickyArea.js
Labels: Status: 리뷰 요청

#23 [Fix] conflict 해결
  src/components/FlexibleSlider/FlexibleSlider.js
  src/config/config.json
  src/customlib/getUserToken.js
  src/pages/Main/FlexibleSliderDetails/MainBestIconDetail.js
  src/pages/Main/FlexibleSliderDetails/MainMdRecommendDetail.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainFlexSliderFetch.js
  src/pages/Main/MainStickyArea.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#21 [28기 김용선][Refactor] merge된 타 branch 리뷰 사항 반영
  public/data/itemData.json
  src/Router.js
  src/components/ProductList/CategoryButton.js
  src/components/ProductList/FilterButton.js
  src/components/ProductList/MainContainer.js
  src/pages/Main/FlexibleSliderHeader/MainMdRecommendHeader.js
  src/pages/Main/Main.scss
  src/pages/Main/MainFlexSliderFetch.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: Status: 리뷰 요청

#22 [28기 강희원][Add] 백엔드 통신중, 삭제 및 구매하기 기능 추가, 장바구니 비어 있는 컴포넌트 추가
  public/data/cartList/cartList.json
  src/pages/Cart/Cart.js
  src/pages/Cart/CartContent.js
  src/pages/Cart/CartList.js
  src/pages/Cart/EmptyCart.js
  src/pages/Cart/EmptyCart.scss
  src/pages/Cart/ProductPrice.js
  src/pages/Cart/SelectCart.js
Labels: Status: 리뷰 요청

#24 [28기 이석호] Add: 리팩토리 진행중, 장바구니 버튼 연결, useParams 사용, 리뷰 별 개수 구현
  src/Router.js
  src/pages/ProductDetail/ProductContent/ProductContent.js
  src/pages/ProductDetail/ProductContent/ProductContent.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductExplain/ProductExplain.js
  src/pages/ProductDetail/ProductExplain/ProductExplain.scss
  src/pages/ProductDetail/SlideShow/SlideShow.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#25 [28기 김정현][Refactor] flexSlider head text strong 부여
  src/pages/Main/FlexibleSliderHeader/MainMdRecommendHeader.js
  src/pages/Main/Main.scss
  src/pages/Main/MainFlexSlider.js
Labels: Status: 리뷰 요청

#26 [28기 김정현][Refactor] hiddenMenu css 수정
  src/components/Nav/Nav.js
  src/components/Nav/NavHiddenMenu.js
  src/components/Nav/NavHiddenVertical/VerticalContent.scss
  src/components/Nav/NavHiddenVertical/VerticalItems.js
Labels: Status: 리뷰 요청

#27 [28기 강희원][Add] 장바구니 전체 및 선택 삭제, 제품 직접 삭제, 구매하기, 장바구니 제품 없을 때 화면 구현
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartContent.js
  src/pages/Cart/CartList.js
  src/pages/Cart/EmptyCart.js
  src/pages/Cart/EmptyCart.scss
  src/pages/Cart/ProductPrice.js
  src/pages/Login/Login.js
  src/pages/Register/Register.js
Labels: Status: 리뷰 요청
